Vagrant.configure("2") do |config|

  config.vm.box      = "ubuntu/jammy64"
  config.vm.hostname = "kernel-lab"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "kernel-compile-lab"
    vb.cpus   = 4
    vb.memory = 4096
  end

end
